name: landsat
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.3
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.4
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - cartopy=0.21.1
  - cfitsio=4.2.0
  - charset-normalizer=3.1.0
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.1.3
  - contourpy=1.1.0
  - curl=8.1.2
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - fiona=1.9.4
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.7.0
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.7.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - ipykernel=6.23.3
  - ipython=8.14.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - json-c=0.16
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - kealib=1.5.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.0
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libpq=15.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munch=3.0.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.25.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.2
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.8.0
  - pooch=1.7.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.1.0
  - pyproj=3.6.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pyzmq=25.1.0
  - rasterio=1.3.7
  - readline=8.2
  - requests=2.31.0
  - rtree=1.0.1
  - scikit-learn=1.2.2
  - scipy=1.11.0
  - setuptools=68.0.0
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.42.0
  - stack_data=0.6.2
  - threadpoolctl=3.1.0
  - tiledb=2.13.2
  - tk=8.6.12
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzcode=2023c
  - tzdata=2023c
  - unicodedata2=15.0.0
  - wcwidth=0.2.6
  - wheel=0.40.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiobotocore==2.5.1
      - aiohttp==3.8.4
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - antimeridian==0.2.6
      - appdirs==1.4.4
      - asarapi==0.6
      - asf-search==6.6.0
      - async-timeout==4.0.2
      - beautifulsoup4==4.12.2
      - botocore==1.29.161
      - bounded-pool-executor==0.0.3
      - bs4==0.0.1
      - certifi==2023.5.7
      - click==7.1.2
      - dateparser==1.1.8
      - distinctipy==1.2.2
      - earthaccess==0.5.2
      - earthdata==0.4.2
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - geojson==3.0.1
      - geomet==1.0.0
      - h5py==3.9.0
      - html2text==2020.1.16
      - hyp3-sdk==2.1.1
      - ijson==3.2.2
      - jmespath==1.0.1
      - landsatxplore
      - lxml==4.9.3
      - multidict==6.0.4
      - multimethod==1.9.1
      - opencv-python==4.8.0.74
      - pqdm==0.2.0
      - pvlib==0.9.5
      - py-eodms-rapi==1.5.5
      - pyarrow==12.0.1
      - python-cmr==0.7.0
      - regex==2023.6.3
      - remotezip==0.12.1
      - s3fs==2023.6.0
      - seaborn==0.12.2
      - sentinelsat==1.2.1
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tinynetrc==1.3.1
      - tqdm==4.65.0
      - tzlocal==5.0.1
      - urllib3==1.26.16
      - wrapt==1.15.0
      - yarl==1.9.2
